[package]
cairo-version = "=2.10.1"
name = "death_mountain"
version = "0.1.0"
edition = "2024_07"

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0" }
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"
game_components_minigame = { git = "https://github.com/Provable-Games/game-components", tag = "0.0.10" }
game_components_metagame = { git = "https://github.com/Provable-Games/game-components", tag = "0.0.10" }
game_components_test_starknet = { git = "https://github.com/Provable-Games/game-components", tag = "0.0.10" }
game_components_token = { git = "https://github.com/Provable-Games/game-components", tag = "0.0.10" }
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "v0.3.0" }
graffiti = { git = "https://github.com/ponderingdemocritus/graffiti", rev = "bc569531791dbc71c6cd8d9bc154c34eedad31fe" }


[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0" }

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "game_components_token::examples::full_token_contract::FullTokenContract",
    "game_components_token::examples::minigame_registry_contract::MinigameRegistryContract",
]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[profile.sepolia]
[profile.slot]
[profile.mainnet]
